[book]
authors = ["Ayoub EL Mhamdi"]
language = "fr"
multilingual = false
src = "src"
title = "Contrôle qualité en radiothérapie"

[build]
create-missing = false
build-dir = "book/html"

[output.html]
site-url = "/CQ/"
no-section-label = true
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/ayoubelmhamdi/CQ"
edit-url-template = "https://github.com/ayoubelmhamdi/CQ/tree/master/{path}"
additional-css = ["./theme/tabbed-code-blocks.css"]
additional-js = ["./theme/tabbed-code-blocks.js", "./theme/highlight.css"]


# mathjax-support = true
[output.katex]
[preprocessor.katex]

# [output.linkcheck]
# optional = true
# warning-policy = "warn"
# traverse-parent-directories = true
# follow-web-links = true
